{
 "title": "Comparison",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Comparison metadata",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select configname, uuid as UUID, track as Track, vehicleclass, vehiclename, driver as Driver, racedate, racetime from raceanalysis.racemetadata \n\nWHERE uuid in (select uuid from raceanalysis.comparison)\n\ngroup by configname, uuid, track, vehicleclass, vehiclename, driver, racedate, racetime, samplespersec, duration\n",
     "rawQuery": "select configname, uuid as UUID, track as Track, vehicleclass, vehiclename, driver as Driver, racedate, racetime from raceanalysis.racemetadata \n\nWHERE uuid in (select uuid from raceanalysis.comparison)\n\ngroup by configname, uuid, track, vehicleclass, vehiclename, driver, racedate, racetime, samplespersec, duration",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Total laps",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    raceid as RaceID,\n    max(lapnumber) - min(lapnumber) as Laps,\n    (max(lapnumber) - min(lapnumber)) * 4.088 as Distance,\n    avg(groundspeed) as Speed,\n    max(timepoint) as TotalTime\nFROM $table\n\nWHERE RaceID in (select uuid from raceanalysis.comparison)\nGROUP BY RaceID\nORDER BY RaceID\n",
     "rawQuery": "SELECT\n    raceid as RaceID,\n    max(lapnumber) - min(lapnumber) as Laps,\n    (max(lapnumber) - min(lapnumber)) * 4.088 as Distance,\n    avg(groundspeed) as Speed,\n    max(timepoint) as TotalTime\nFROM raceanalysis.racedata\n\nWHERE RaceID in (select uuid from raceanalysis.comparison)\nGROUP BY RaceID\nORDER BY RaceID",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Max tyre wear",
   "type": "table",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select arrayMax(arr) as MaxTyreWear  from (\n  select raceid, array(LeftFrontTyre, RightFrontTyre, LeftRearTyre, RightRearTyre) as arr from (\n    SELECT\n      raceid,\n      max(tyrefl) as LeftFrontTyre,\n      max(tyrefr) as RightFrontTyre,\n      max(tyrerl) as LeftRearTyre,\n      max(tyrerr) as RightRearTyre\n    FROM raceanalysis.racedata\n\n    WHERE raceid in (select uuid from raceanalysis.comparison)\n    group by raceid\n  )\n  group by arr, raceid\n)\ngroup by raceid, arr\nORDER BY raceid",
     "rawQuery": "select arrayMax(arr) as MaxTyreWear  from (\n  select raceid, array(LeftFrontTyre, RightFrontTyre, LeftRearTyre, RightRearTyre) as arr from (\n    SELECT\n      raceid,\n      max(tyrefl) as LeftFrontTyre,\n      max(tyrefr) as RightFrontTyre,\n      max(tyrerl) as LeftRearTyre,\n      max(tyrerr) as RightRearTyre\n    FROM raceanalysis.racedata\n\n    WHERE raceid in (select uuid from raceanalysis.comparison)\n    group by raceid\n  )\n  group by arr, raceid\n)\ngroup by raceid, arr\nORDER BY raceid",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Avg fuel consumption per lap",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select avg(Fuel) from (\nSELECT\n    raceid,\n    max(fulel) - min(fulel) as Fuel\nFROM $table\n\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY lapnumber, raceid\nORDER BY lapnumber\n) where Fuel < 50\n\nGROUP BY raceid\nORDER BY raceid",
     "rawQuery": "select avg(Fuel) from (\nSELECT\n    raceid,\n    max(fulel) - min(fulel) as Fuel\nFROM raceanalysis.racedata\n\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY lapnumber, raceid\nORDER BY lapnumber\n) where Fuel < 50\n\nGROUP BY raceid\nORDER BY raceid",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Avg lap time",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select avg(Fuel) from (\nSELECT\n    raceid,\n    max(timepoint) - min(timepoint) as Fuel\nFROM $table\n\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY lapnumber, raceid\nORDER BY lapnumber\n)\n\nGROUP BY raceid\nORDER BY raceid",
     "rawQuery": "select avg(Fuel) from (\nSELECT\n    raceid,\n    max(timepoint) - min(timepoint) as Fuel\nFROM raceanalysis.racedata\n\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY lapnumber, raceid\nORDER BY lapnumber\n)\n\nGROUP BY raceid\nORDER BY raceid",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Average tyre wear per lap",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select arrayAvg(arr) as AvgTyreWearPerLap  from (\n  select raceid, array(avg(LeftFrontTyre), avg(RightFrontTyre), avg(LeftRearTyre), avg(RightRearTyre)) as arr from (\n    SELECT\n      raceid,\n      max(tyrefl) - min(tyrefl) as LeftFrontTyre,\n      max(tyrefr) - min(tyrefr) as RightFrontTyre,\n      max(tyrerl) - min(tyrerl) as LeftRearTyre,\n      max(tyrerr) - min(tyrerr) as RightRearTyre\n    FROM raceanalysis.racedata\n\n    WHERE raceid in (select uuid from raceanalysis.comparison)\n\n    GROUP BY raceid, lapnumber\n\n    ORDER BY raceid, lapnumber\n  ) as SHIT\nwhere \nSHIT.LeftFrontTyre < 10 and SHIT.RightFrontTyre < 10 and SHIT.LeftRearTyre < 10 and SHIT.RightRearTyre < 10\nGROUP by raceid\n)\nORDER BY raceid",
     "rawQuery": "select arrayAvg(arr) as AvgTyreWearPerLap  from (\n  select raceid, array(avg(LeftFrontTyre), avg(RightFrontTyre), avg(LeftRearTyre), avg(RightRearTyre)) as arr from (\n    SELECT\n      raceid,\n      max(tyrefl) - min(tyrefl) as LeftFrontTyre,\n      max(tyrefr) - min(tyrefr) as RightFrontTyre,\n      max(tyrerl) - min(tyrerl) as LeftRearTyre,\n      max(tyrerr) - min(tyrerr) as RightRearTyre\n    FROM raceanalysis.racedata\n\n    WHERE raceid in (select uuid from raceanalysis.comparison)\n\n    GROUP BY raceid, lapnumber\n\n    ORDER BY raceid, lapnumber\n  ) as SHIT\nwhere \nSHIT.LeftFrontTyre < 10 and SHIT.RightFrontTyre < 10 and SHIT.LeftRearTyre < 10 and SHIT.RightRearTyre < 10\nGROUP by raceid\n)\nORDER BY raceid",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Fuel pitstops",
   "type": "table",
   "gridPos": { "h": 26, "w": 4, "x": 19, "y": 6 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT raceid, Lap from (\nSELECT\n    raceid,\n    lapnumber as Lap,\n    max(fulel) - min(fulel) as FD\nFROM $table\n\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY raceid, lapnumber\n\nORDER BY raceid, lapnumber\n) where FD > 50",
     "rawQuery": "SELECT raceid, Lap from (\nSELECT\n    raceid,\n    lapnumber as Lap,\n    max(fulel) - min(fulel) as FD\nFROM raceanalysis.racedata\n\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY raceid, lapnumber\n\nORDER BY raceid, lapnumber\n) where FD > 50",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Lap time chart",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select *, runningDifference(LapTime) as dlt from (\nSELECT\n    raceid,\n    lapnumber,\n    max(timepoint) - min(timepoint) as LapTime,\n    max(fulel) - min(fulel) as FD\nFROM $table\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY raceid, lapnumber\nORDER BY raceid, lapnumber\n) where FD < 5.0 and dlt < 6.0\nGROUP BY raceid, lapnumber, LapTime, FD\nORDER BY raceid, lapnumber",
     "rawQuery": "select *, runningDifference(LapTime) as dlt from (\nSELECT\n    raceid,\n    lapnumber,\n    max(timepoint) - min(timepoint) as LapTime,\n    max(fulel) - min(fulel) as FD\nFROM raceanalysis.racedata\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY raceid, lapnumber\nORDER BY raceid, lapnumber\n) where FD < 5.0 and dlt < 6.0\nGROUP BY raceid, lapnumber, LapTime, FD\nORDER BY raceid, lapnumber",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Time wear by lap",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 23 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from (\nSELECT\n    raceid,\n    lapnumber,\n    max(tyrefl) as TyreFL,\n    max(tyrefr) as TyreFR,\n    max(tyrerl) as TyreRL,\n    max(tyrerr) as TyreRR,\n    max(fulel) - min(fulel) as FD\nFROM $table\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY raceid, lapnumber\nORDER BY raceid, lapnumber\n) where FD < 5.0",
     "rawQuery": "select * from (\nSELECT\n    raceid,\n    lapnumber,\n    max(tyrefl) as TyreFL,\n    max(tyrefr) as TyreFR,\n    max(tyrerl) as TyreRL,\n    max(tyrerr) as TyreRR,\n    max(fulel) - min(fulel) as FD\nFROM raceanalysis.racedata\nWHERE raceid in (select uuid from raceanalysis.comparison)\n\nGROUP BY raceid, lapnumber\nORDER BY raceid, lapnumber\n) where FD < 5.0",
     "round": "0s",
     "table": "racedata"
    }
   ]
  }
 ]
}