{
 "title": "Last upload",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total laps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    DISTINCT lapnumber as Lap\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n",
     "rawQuery": "SELECT\n    DISTINCT lapnumber as Lap\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (max(lapnumber) - min(lapnumber)) * 4.088 as Distance\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n",
     "rawQuery": "SELECT\n    (max(lapnumber) - min(lapnumber)) * 4.088 as Distance\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Ground speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    avg(groundspeed) as Distance\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Total time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    max(timepoint) as LastTime\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n",
     "rawQuery": "SELECT\n    max(timepoint) as LastTime\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Max tyre wear",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select arrayMax(arr) as MaxTyreWear  from (\n  select array(LeftFrontTyre, RightFrontTyre, LeftRearTyre, RightRearTyre) as arr from (\n    SELECT\n      max(tyrefl) as LeftFrontTyre,\n      max(tyrefr) as RightFrontTyre,\n      max(tyrerl) as LeftRearTyre,\n      max(tyrerr) as RightRearTyre\n    FROM raceanalysis.racedata\n\n    WHERE raceid = (select id from raceanalysis.last)\n  )\n)",
     "rawQuery": "select arrayMax(arr) as MaxTyreWear  from (\n  select array(LeftFrontTyre, RightFrontTyre, LeftRearTyre, RightRearTyre) as arr from (\n    SELECT\n      max(tyrefl) as LeftFrontTyre,\n      max(tyrefr) as RightFrontTyre,\n      max(tyrerl) as LeftRearTyre,\n      max(tyrerr) as RightRearTyre\n    FROM raceanalysis.racedata\n\n    WHERE raceid = (select id from raceanalysis.last)\n  )\n)",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Average fuel consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select avg(Fuel) from (\nSELECT\n    max(fulel) - min(fulel) as Fuel\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n) where Fuel < 50",
     "rawQuery": "select avg(Fuel) from (\nSELECT\n    max(fulel) - min(fulel) as Fuel\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n) where Fuel < 50",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Average lap time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    max(timepoint) - min(timepoint) as LapTime\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n",
     "rawQuery": "SELECT\n    max(timepoint) - min(timepoint) as LapTime\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Average tyre wear per lap",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select arrayAvg(arr) as AvgTyreWearPerLap  from (\nselect array(avg(LeftFrontTyre), avg(RightFrontTyre), avg(LeftRearTyre), avg(RightRearTyre)) as arr from (\nSELECT\n  max(tyrefl) - min(tyrefl) as LeftFrontTyre,\n  max(tyrefr) - min(tyrefr) as RightFrontTyre,\n  max(tyrerl) - min(tyrerl) as LeftRearTyre,\n  max(tyrerr) - min(tyrerr) as RightRearTyre\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n)\nwhere \nLeftFrontTyre < 10 and RightFrontTyre < 10 and LeftRearTyre < 10 and RightRearTyre < 10\n)",
     "rawQuery": "select arrayAvg(arr) as AvgTyreWearPerLap  from (\nselect array(avg(LeftFrontTyre), avg(RightFrontTyre), avg(LeftRearTyre), avg(RightRearTyre)) as arr from (\nSELECT\n  max(tyrefl) - min(tyrefl) as LeftFrontTyre,\n  max(tyrefr) - min(tyrefr) as RightFrontTyre,\n  max(tyrerl) - min(tyrerl) as LeftRearTyre,\n  max(tyrerr) - min(tyrerr) as RightRearTyre\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n)\nwhere \nLeftFrontTyre < 10 and RightFrontTyre < 10 and LeftRearTyre < 10 and RightRearTyre < 10\n)",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Average lap time without pits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select *, runningDifference(LapTime) as dlt from (\nSELECT\n    raceid,\n    lapnumber,\n    max(timepoint) - min(timepoint) as LapTime,\n    max(fulel) - min(fulel) as FD\nFROM $table\nWHERE raceid in (select id from raceanalysis.last)\n\nGROUP BY raceid, lapnumber\nORDER BY raceid, lapnumber\n) where FD < 5.0 and dlt < 6.0\nGROUP BY raceid, lapnumber, LapTime, FD\nORDER BY raceid, lapnumber",
     "rawQuery": "select *, runningDifference(LapTime) as dlt from (\nSELECT\n    raceid,\n    lapnumber,\n    max(timepoint) - min(timepoint) as LapTime,\n    max(fulel) - min(fulel) as FD\nFROM raceanalysis.racedata\nWHERE raceid in (select id from raceanalysis.last)\n\nGROUP BY raceid, lapnumber\nORDER BY raceid, lapnumber\n) where FD < 5.0 and dlt < 6.0\nGROUP BY raceid, lapnumber, LapTime, FD\nORDER BY raceid, lapnumber",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Fuel level by lap",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeColDataType": "raceid",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  lapnumber,\n  avg(fulel) as FuelLevel\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n",
     "rawQuery": "SELECT\n  lapnumber,\n  avg(fulel) as FuelLevel\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Lap time chart",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select *, runningDifference(T) as dT from (\nSELECT\n    lapnumber,\n    max(timepoint) - min(timepoint) as T\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n) where dT < 5.0",
     "rawQuery": "select *, runningDifference(T) as dT from (\nSELECT\n    lapnumber,\n    max(timepoint) - min(timepoint) as T\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n) where dT < 5.0",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Tyre pitstops",
   "type": "table",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 22 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Lap from (\nSELECT\n    raceid,\n    lapnumber as Lap,\n    max(tyrefl) - min(tyrefl) as FD\nFROM $table\n\nWHERE raceid in (select id from raceanalysis.last)\n\nGROUP BY raceid, lapnumber\n\nORDER BY raceid, lapnumber\n) where FD > 2.0",
     "rawQuery": "SELECT Lap from (\nSELECT\n    raceid,\n    lapnumber as Lap,\n    max(tyrefl) - min(tyrefl) as FD\nFROM raceanalysis.racedata\n\nWHERE raceid in (select id from raceanalysis.last)\n\nGROUP BY raceid, lapnumber\n\nORDER BY raceid, lapnumber\n) where FD > 2.0",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Fuel pitstops",
   "type": "table",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 22 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select Lap from (\nSELECT\n    lapnumber as Lap,\n    deltaSum(fulel) as FD\nFROM $table\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n)\nwhere FD > 20",
     "rawQuery": "select Lap from (\nSELECT\n    lapnumber as Lap,\n    deltaSum(fulel) as FD\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY lapnumber\n\nORDER BY lapnumber\n)\nwhere FD > 20",
     "round": "0s",
     "table": "racedata"
    }
   ]
  },
  {
   "title": "Tyre wear over laps",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 22 },
   "targets": [
    {
     "database": "raceanalysis",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  lapnumber as Lap,\n  avg(fulel) as FuelLevel,\n  avg(tyrefl) as LeftFrontTyre,\n  avg(tyrefr) as RightFrontTyre,\n  avg(tyrerl) as LeftRearTyre,\n  avg(tyrerr) as RightRearTyre\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY Lap\n\nORDER BY Lap\n",
     "rawQuery": "SELECT\n  lapnumber as Lap,\n  avg(fulel) as FuelLevel,\n  avg(tyrefl) as LeftFrontTyre,\n  avg(tyrefr) as RightFrontTyre,\n  avg(tyrerl) as LeftRearTyre,\n  avg(tyrerr) as RightRearTyre\nFROM raceanalysis.racedata\n\nWHERE raceid = (select id from raceanalysis.last)\n\nGROUP BY Lap\n\nORDER BY Lap",
     "round": "0s",
     "table": "racedata"
    }
   ]
  }
 ]
}